# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('rawname', models.CharField(max_length=128)),
                ('classname', models.CharField(max_length=128)),
                ('racename', models.CharField(max_length=128)),
                ('realmrank', models.CharField(max_length=128)),
                ('guildname', models.CharField(max_length=128)),
                ('raw_data', models.CharField(max_length=512)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical player',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('rawname', models.CharField(max_length=128)),
                ('classname', models.CharField(max_length=128)),
                ('racename', models.CharField(max_length=128)),
                ('realmrank', models.CharField(max_length=128)),
                ('guildname', models.CharField(max_length=128)),
                ('raw_data', models.CharField(max_length=512)),
            ],
        ),
    ]
