# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='realmname',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='realmname',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
