# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0002_auto_20170202_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayer',
            name='rawname',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='rawname',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
