# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0003_auto_20170202_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='rps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rps',
            field=models.IntegerField(null=True),
        ),
    ]
