# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0004_auto_20170202_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='xp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(null=True),
        ),
    ]
