# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0005_auto_20170202_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayer',
            name='rps',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalplayer',
            name='xp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rps',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.BigIntegerField(null=True),
        ),
    ]
