# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0008_auto_20170202_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='lastupdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='lastupdated',
            field=models.DateTimeField(null=True),
        ),
    ]
