# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0011_dfalls_historicaldfalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkeep',
            name='location',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keep',
            name='location',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
