# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hellocount', '0012_auto_20170210_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRelic',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('lastupdated', models.DateTimeField(null=True)),
                ('origin', models.CharField(max_length=128)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical relic',
            },
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('lastupdated', models.DateTimeField(null=True)),
                ('origin', models.CharField(max_length=128)),
            ],
        ),
    ]
