# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0014_auto_20170220_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplayer',
            name='classname',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalplayer',
            name='guildname',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplayer',
            name='racename',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalplayer',
            name='realmname',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='classname',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='guildname',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='racename',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='realmname',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
