# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellocount', '0016_auto_20170228_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayer',
            name='global_rank',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='global_rank',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
